{
    "name": "MX Finance Core",
    "version": "16.0.1.0.0",
    "summary": "Multi-ledger accounting base for Mexico (NIF/SAT + IFRS)",
    "category": "Accounting",
    "author": "Finance Team",
    "depends": ["base", "account", "mail"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/ledger_data.xml",
        "views/ledger_views.xml",
        "views/account_account_views.xml",
        "views/policy_rule_views.xml",
        "views/accounting_event_views.xml",
        "views/posting_run_views.xml",
        "views/close_period_views.xml",
        "views/account_period_lock_views.xml",
        "views/fiscal_document_views.xml",
        "views/sat_compliance_views.xml",
        "views/journal_import_views.xml",
        "views/lease_views.xml",
        "views/dimension_set_views.xml",
        "views/rate_table_views.xml",
        "views/fx_revaluation_views.xml",
        "views/reporting_template_views.xml",
        "views/ifrs18_views.xml",
        "views/statement_package_views.xml",
        "views/group_structure_views.xml",
        "views/consolidation_views.xml",
        "views/intercompany_views.xml",
        "views/hedge_views.xml",
        "views/close_cockpit_views.xml",
        "views/internal_control_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
